name: Meson

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  meson-build:
    name: Build and Clang-Tidy
    runs-on: ubuntu-latest
    env:
      CC: clang-21
      CXX: clang++-21
      CXXFLAGS: -stdlib=libc++
      LDFLAGS: -stdlib=libc++

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          meson \
          ninja-build \
          pkg-config \
          libjwt-dev \
          libcurl4-openssl-dev \
          libssl-dev \
          libreadline-dev \
          zlib1g-dev \
          libxml2-dev \
          libxslt1-dev \
          uuid-dev \
          flex \
          bison
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21 all
        sudo apt-get install libc++-21-dev libc++abi-21-dev clang-tidy-21

    - name: Checkout PostgreSQL source
      uses: actions/checkout@v4
      with:
        repository: postgres/postgres
        ref: REL_18_STABLE
        path: pg-source
        submodules: recursive

    - name: Checkout pg_oauth extension
      uses: actions/checkout@v4
      with:
        path: pg-source/contrib/pg_oauth
        submodules: true

    - name: Add pg_oauth to contrib meson.build
      run: |
        cd pg-source
        echo "subdir('pg_oauth')" >> contrib/meson.build

    - name: Configure with meson
      run: |
        cd pg-source
        meson setup build \
          --buildtype=debug \
          -Dprefix=/usr/local/pgsql

    - name: Build PostgreSQL with pg_oauth
      run: |
        cd pg-source
        ninja -C build

    - name: Run clang-tidy on pg_oauth sources
      run: |
        cd pg-source
        cp build/compile_commands.json .
        cd contrib/pg_oauth
        clang-tidy-21 src/*
